-- SQL DDL Skeleton
-- Project: Smart CRM - L02
-- Database: PostgreSQL

-- 1. CUSTOMER
CREATE TABLE customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(10) NOT NULL UNIQUE,
    address VARCHAR(255),
    CONSTRAINT ck_customer_phone
        CHECK (phone ~ '^0[0-9]{9}$')
);

-- 2. ISSUE_CATEGORY
CREATE TABLE issue_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(30) NOT NULL UNIQUE,
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_issue_category_code
        CHECK (category_code IN (
            'MAN_HINH',
            'PIN',
            'SAC',
            'PHAN_MEM',
            'NUOC_VAO',
            'KHAC'
        ))
);

-- 3. SERVICE_CENTER
CREATE TABLE service_center (
    center_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 4. DEVICE
CREATE TABLE device (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    serial_no VARCHAR(50) NOT NULL UNIQUE,
    purchase_date DATE,
    warranty_months INTEGER NOT NULL,

    CONSTRAINT fk_device_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(customer_id),

    CONSTRAINT ck_device_warranty_months
        CHECK (warranty_months > 0),

    CONSTRAINT uq_device_customer
        UNIQUE (device_id, customer_id)
);

-- product_id refers to the product catalog, which is
-- outside the six-table scope of this ERD.

-- 5. TICKET
CREATE TABLE ticket (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    center_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    issue_desc VARCHAR(2000) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'MOI',
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMPTZ NOT NULL,
    accessories JSONB,

    CONSTRAINT fk_ticket_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(customer_id),

    CONSTRAINT fk_ticket_device_customer
        FOREIGN KEY (device_id, customer_id)
        REFERENCES device(device_id, customer_id),

    CONSTRAINT fk_ticket_center
        FOREIGN KEY (center_id)
        REFERENCES service_center(center_id),

    CONSTRAINT fk_ticket_category
        FOREIGN KEY (category_id)
        REFERENCES issue_category(category_id),

    CONSTRAINT ck_ticket_issue_desc
        CHECK (char_length(issue_desc) BETWEEN 10 AND 2000),

    CONSTRAINT ck_ticket_priority
        CHECK (priority IN ('CAO', 'TRUNG_BINH', 'THAP')),

    CONSTRAINT ck_ticket_status
        CHECK (status IN (
            'MOI',
            'DANG_XU_LY',
            'CHO_LINH_KIEN',
            'DA_SUA',
            'DA_GIAO',
            'HUY'
        )),

    CONSTRAINT ck_ticket_accessories
        CHECK (
            accessories IS NULL
            OR jsonb_typeof(accessories) = 'array'
        )
);

-- 6. TICKET_STATUS_LOG
CREATE TABLE ticket_status_log (
    status_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    old_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(255),

    CONSTRAINT fk_status_log_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES ticket(ticket_id),

    CONSTRAINT ck_status_log_new_status
        CHECK (new_status IN (
            'MOI',
            'DANG_XU_LY',
            'CHO_LINH_KIEN',
            'DA_SUA',
            'DA_GIAO',
            'HUY'
        ))
);

-- Indexes supporting ticket lookup and listing
CREATE INDEX idx_ticket_customer_id
    ON ticket(customer_id);

CREATE INDEX idx_ticket_device_id
    ON ticket(device_id);

CREATE INDEX idx_ticket_received_at
    ON ticket(received_at);

CREATE INDEX idx_ticket_status_due_date
    ON ticket(status, due_date);

CREATE INDEX idx_device_customer_id
    ON device(customer_id);